### ISSUE TITLE
default key format

### ISSUE THREAD

**Issue by mjpost** [mjpost/bibsearch#20]
We should have a discussion about the default key format.

Google Scholar seems to use last name, full year, and first word of the paper, e.g., `brown1993mathematics`. I've been using this for a while and am accustomed to it.

Current bib search default is `brown93_mathematics`. Collisions are handled by appending a letter after the year.

I would like to argue for `brown:1993:mathematics`, which I find nicely balances information and aesthetics. 

I would also like to suggest that we handled collisions by adding another word of the title.

Of course, this is all somewhat moot with the custom key format, but we should have a good default.

**Comment by davvil** [comment]
My personal style is "brown93:mathematics". Of course manually I select a "better word" (I think I have it as "brown93:MT"), but I don't think we want to include a text summarization module in bibsearch :-P

I don't have strong feelings for an alternative, but rather some guidelines:
* I prefer having one separator (and only one), I don't really like "brown1993mathematics" or "brown:1993:mathematics", but I don't have strong feelings for either : or _.
* I'd rather have single letter disambiguation, "brown1993:mathematics_machine" seems a bit cumbersome.
* I slightly prefer 2 digit years.
* I'm ambivalent about including etAl.

**Comment by mjpost** [comment]
Offline discussion led to "{surname}{year}{suffix}:{title}".
