### ISSUE TITLE
Edit doesn't work

### ISSUE THREAD

**Issue by davvil** [mjpost/bibsearch#31]
`original_key` is not output into the bib entries. Edit relies on this field to identify the entries, so editing does not work.

**Comment by texttheater** [comment]
`bibsearch edit $SEARCHTERM` always gives me just an empty file to edit.

**Comment by mjpost** [comment]
Hmm, this is true for me, too. I know this was working recently. We'll take a look.

**Comment by davvil** [comment]
Solved in a24d835.
