### ISSUE TITLE
Manually added bibliography entries + bib file generation?

### ISSUE THREAD

**Issue by texttheater** [mjpost/bibsearch#39]
Is there any way to use automatic bib file generation but also use manually added bibliography entries? At the moment there seems to be only the choice between `bibsearch tex -b` which refuses to write to an existing bib file if there is one, and `bibsearch tex -B` which will destroy manually added entries. Seems to me the best behavior would be to just append to the bib file entries that are not yet in it.

**Comment by mjpost** [comment]
You can add the manual ones to your bibsearch DB with “bibsearch add”. You could also pull in multiple bib files in the latex—your file of manual entries, plus the file generated by bibsearch.

**Comment by texttheater** [comment]
Thanks!
